# constants

PERCENTAGE_BUILTIN_SLOTS = 0.20

# Time
FOUNTAIN_MONTH = 'FOUNTAIN:MONTH'
FOUNTAIN_WEEKDAY = 'FOUNTAIN:WEEKDAY'
FOUNTAIN_HOLIDAYS = 'FOUNTAIN:HOLIDAYS'
FOUNTAIN_MONTH_DAY = 'FOUNTAIN:MONTH_DAY'
FOUNTAIN_TIME = 'FOUNTAIN:TIME'
FOUNTAIN_NUMBER = 'FOUNTAIN:NUMBER'
FOUNTAIN_DATE = 'FOUNTAIN:DATE'

# Location
FOUNTAIN_CITY = 'FOUNTAIN:CITY'
FOUNTAIN_COUNTRY = 'FOUNTAIN:COUNTRY'
FOUNTAIN_EDU_ORGANIZATION = 'FOUNTAIN:EDU_ORGANIZATION'
FOUNTAIN_ADMIN_ORGANIZATION = 'FOUNTAIN:ADMIN_ORGANIZATION'
FOUNTAIN_NONPROFIT_ORGANIZATION = 'FOUNTAIN:NONPROFIT_ORGANIZATION'
FOUNTAIN_ROOM = 'FOUNTAIN:ROOM'

# Demographics
FOUNTAIN_FAMOUSPEOPLE = 'FOUNTAIN:FAMOUSPEOPLE'
FOUNTAIN_MALE_FIRSTNAME = 'FOUNTAIN:MALE_FIRSTNAME'
FOUNTAIN_FEMALE_FIRSTNAME = 'FOUNTAIN:FEMALE_FIRSTNAME'
FOUNTAIN_NAME = 'FOUNTAIN:FEMALE_FIRSTNAME'
FOUNTAIN_LANGUAGE = 'FOUNTAIN:LANGUAGE'
FOUNTAIN_PROFESSION = 'FOUNTAIN:PROFESSION'

# Culture
FOUNTAIN_BOOK = 'FOUNTAIN:BOOK'
FOUNTAIN_ARTIST = 'FOUNTAIN:ARTIST'
FOUNTAIN_AUTHOR = 'FOUNTAIN:AUTHOR'

# Media
FOUNTAIN_TV_CHANNEL = 'FOUNTAIN:TV_CHANNEL'
FOUNTAIN_TV_SHOW = 'FOUNTAIN:TV_SHOW'
FOUNTAIN_RADIO_CHANNEL = 'FOUNTAIN:RADIO_CHANNEL'
FOUNTAIN_MOVIE = 'FOUNTAIN:MOVIE'
FOUNTAIN_MOVIE_SERIE = 'FOUNTAIN:MOVIE_SERIE'
FOUNTAIN_MUSIC_ALBUM = 'FOUNTAIN:MUSIC_ALBUM'
FOUNTAIN_MUSIC_EVENT = 'FOUNTAIN:MUSIC_EVENT'

# Food
FOUNTAIN_FRUIT = 'FOUNTAIN:FRUITS'
FOUNTAIN_DRINK = 'FOUNTAIN:DRINK'
FOUNTAIN_MEAL = 'FOUNTAIN:MEAL'

# EVENTS
FOUNTAIN_EVENT_TYPE = 'FOUNTAIN:EVENT_TYPE'
FOUNTAIN_GENRE = 'FOUNTAIN:GENRE'

# Tech
FOUNTAIN_MOBILE_APP = 'FOUNTAIN:MOBILE_APP'
FOUNTAIN_GAME = 'FOUNTAIN:GAME'
FOUNTAIN_SOCIAL_PLATFORM = 'FOUNTAIN:SOCIAL_PLATFORM'

# MISC
FOUNTAIN_COLOR = 'FOUNTAIN:COLOR'
FOUNTAIN_DEVICE = 'FOUNTAIN:DEVICE'
FOUNTAIN_SPORT = 'FOUNTAIN:SPORT'

FOUNTAIN_BUILTIN = {FOUNTAIN_FEMALE_FIRSTNAME, FOUNTAIN_MALE_FIRSTNAME, FOUNTAIN_FAMOUSPEOPLE, FOUNTAIN_CITY, FOUNTAIN_MONTH, FOUNTAIN_WEEKDAY, FOUNTAIN_HOLIDAYS, FOUNTAIN_MONTH_DAY}

RESOURCES = {

    FOUNTAIN_MONTH: "month.csv",
    FOUNTAIN_WEEKDAY: "weekday.csv",
    FOUNTAIN_HOLIDAYS: "holidays.csv",
    FOUNTAIN_MONTH_DAY: "month_day.csv",
    FOUNTAIN_CITY: "city.csv",
    FOUNTAIN_FAMOUSPEOPLE: "famous_people.csv",
    FOUNTAIN_FEMALE_FIRSTNAME: "female_firstnames.csv",
    FOUNTAIN_MALE_FIRSTNAME: "male_firstnames.csv"

}